sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an emage with dockerfile"
  - docker build -t suljiwoo/docker-react-app .

script:
  - docker run -e CI=true suljiwoo/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-461923879445"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
